### ISSUE TITLE
no exported member 'AppComponent'

### ISSUE THREAD

**Issue by robertellis100** [ssuperczynski/ng2-easy-table#22]
app/app.component.spec.ts(2,10): error TS2305: Module '"...{projectName}/app/app.component"' has no exported member 'AppComponent'.

_Attempted to install and implement ng2-easy-table into current project, resulted in above error. Installed fresh version of angular2, then installed and implement ng2-easy-table into the fresh angular2 project, which resulted in the same error above. See that code below._

## **main.ts**
```typescript
import {bootstrap}    from 'angular2/platform/browser';
import {App} from './app.component';

bootstrap(App);
```

## **app.components.ts**
```typescript
import {Component} from 'angular2/core';
import {bootstrap}     from 'angular2/platform/browser';
import {AppComponent}  from 'ng2-easy-table/app/app.component';
import {ConfigService} from "./config-service";

@Component({
    selector: 'app',
    directives: [AppComponent],
    providers: [ConfigService],
    template: `<h1>My First Angular 2 App</h1>
    <ng2-table [configuration]="configuration">
        <tr>
            <td>Name</td>
            <td>Position</td>
            <td>Rank</td>
        </tr>
        <tr>
            <td>Joe</td>
            <td>Quarterback</td>
            <td>10</td>
        </tr>
        <tr>
            <td>Tommy</td>
            <td>Saleperson</td>
            <td>1</td>
        </tr>
        <tr>
            <td>Richard</td>
            <td>Running Back</td>
            <td>4</td>
        </tr>
        <tr>
            <td>Devin</td>
            <td>Developer</td>
            <td>7</td>
        </tr>    
    </ng2-table>
    `
})
export class App { 
    constructor(private configuration:ConfigService) {}
}
bootstrap(App, [ConfigService]);
```
## **config-service.ts**
```typescript
import {Injectable} from "angular2/core";
@Injectable()
export class ConfigService {
    public searchEnabled = true;
    public orderEnabled = true;
    public globalSearchEnabled = false;
    public footerEnabled = false;
    public paginationEnabled = false;
    public exportEnabled = false;
    // etc
}
```

**Comment by ssuperczynski** [comment]
in config-service.ts you need to add `resourceUrl`. For Example:

```ts
import {Injectable} from "angular2/core";
@Injectable()
export class ConfigService {
    public searchEnabled = true;
    public orderEnabled = true;
    public globalSearchEnabled = true;
    public footerEnabled = false;
    public paginationEnabled = true;
    public exportEnabled = true;
    public editEnabled = false;
    public resourceUrl = "app/data.json";
    public rows = 10;
}
```

And then in your app.component.js jest initialie table:

```ts
/// <reference path="../node_modules/angular2/typings/browser.d.ts" />
import {Component} from 'angular2/core';
import {bootstrap}    from 'angular2/platform/browser';
import {AppComponent}    from 'ng2-easy-table/app/app.component';
import {ConfigService} from "./config-service";

@Component({
  selector: 'app',
  directives: [AppComponent],
  providers: [ConfigService],
  template: `
    <ng2-table [configuration]="configuration"></ng2-table>
  `
})
export class App {
  constructor(
    private configuration:ConfigService

  ) {}
}

bootstrap(App, []);
```

`<ng2-table [configuration]="configuration"></ng2-table>` Will render whole table structure from your json. In next release there will ba an option to define custom `<thead>` and `<td>`

**Comment by robertellis100** [comment]
**I followed the changes and no success. Including the 'reference path' results in the following errors:**
node_modules/angular2/typings/browser.d.ts(6,14): error TS2300: Duplicate identifier 'PromiseConstructor'.
node_modules/angular2/typings/es6-collections/es6-collections.d.ts(22,5): error TS2300: Duplicate identifier 'done'.
node_modules/angular2/typings/es6-collections/es6-collections.d.ts(23,5): error TS2300: Duplicate identifier 'value'.
node_modules/angular2/typings/es6-collections/es6-collections.d.ts(46,5): error TS2300: Duplicate identifier 'size'.
node_modules/angular2/typings/es6-collections/es6-collections.d.ts(52,5): error TS2300: Duplicate identifier 'prototype'.
node_modules/angular2/typings/es6-collections/es6-collections.d.ts(66,5): error TS2300: Duplicate identifier 'size'.
node_modules/angular2/typings/es6-collections/es6-collections.d.ts(72,5): error TS2300: Duplicate identifier 'prototype'.
node_modules/angular2/typings/es6-collections/es6-collections.d.ts(88,5): error TS2300: Duplicate identifier 'prototype'.
node_modules/angular2/typings/es6-collections/es6-collections.d.ts(103,5): error TS2300: Duplicate identifier 'prototype'.
node_modules/angular2/typings/es6-promise/es6-promise.d.ts(11,15): error TS2300: Duplicate identifier 'Promise'.
node_modules/angular2/typings/es6-promise/es6-promise.d.ts(42,16): error TS2300: Duplicate identifier 'Promise'.
app/app.component.spec.ts(2,10): error TS2305: Module '"C:/Source/angProj2-table/app/app.component"' has no exported member 'AppComponent'.
typings/browser/ambient/es6-shim/index.d.ts(11,5): error TS2300: Duplicate identifier 'done'.
typings/browser/ambient/es6-shim/index.d.ts(12,5): error TS2300: Duplicate identifier 'value'.
typings/browser/ambient/es6-shim/index.d.ts(477,11): error TS2300: Duplicate identifier 'Promise'.
typings/browser/ambient/es6-shim/index.d.ts(496,11): error TS2300: Duplicate identifier 'PromiseConstructor'.
typings/browser/ambient/es6-shim/index.d.ts(554,13): error TS2300: Duplicate identifier 'Promise'.
typings/browser/ambient/es6-shim/index.d.ts(563,5): error TS2300: Duplicate identifier 'size'.
typings/browser/ambient/es6-shim/index.d.ts(572,5): error TS2300: Duplicate identifier 'prototype'.
typings/browser/ambient/es6-shim/index.d.ts(583,5): error TS2300: Duplicate identifier 'size'.
typings/browser/ambient/es6-shim/index.d.ts(592,5): error TS2300: Duplicate identifier 'prototype'.
typings/browser/ambient/es6-shim/index.d.ts(607,5): error TS2300: Duplicate identifier 'prototype'.
typings/browser/ambient/es6-shim/index.d.ts(621,5): error TS2300: Duplicate identifier 'prototype'.

When the 'reference path' is removed, then the same component export error occurs:
app/app.component.spec.ts(2,10): error TS2305: Module '"...{project}/app/app.component"' has no exported member 'AppComponent'.

**app.components.ts**
`import {Component} from 'angular2/core';
import {bootstrap}    from 'angular2/platform/browser';
import {AppComponent}    from 'ng2-easy-table/app/app.component';
import {ConfigService} from "./config-service";

@Component({
  selector: 'app',
  directives: [AppComponent],
  providers: [ConfigService],
  template: `
    <ng2-table [configuration]="configuration"></ng2-table>
  `
})
export class App {
  constructor(
    private configuration:ConfigService

  ) {}
}

bootstrap(App, []);`

**config-service.ts**
`import {Injectable} from "angular2/core";
@Injectable()
export class ConfigService {
    public searchEnabled = true;
    public orderEnabled = true;
    public globalSearchEnabled = true;
    public footerEnabled = false;
    public paginationEnabled = true;
    public exportEnabled = true;
    public editEnabled = false;
    public resourceUrl = "app/data.json";
    public rows = 10;
}`

**data.json**
`{
    "Name": "Capn Crunch",
    "Author": "Lola",
    "Company List": [
        {"Company": "Amazonia", "MarketCap": "5B", "PotluckItem": "drinks"},
        {"Company": "eBayaria", "MarketCap": "20B", "PotluckItem": "desserts"},
        {"Company": "Softmicrosia", "MarketCap": "60B", "PotluckItem": "salads"}
    ]
}`

**Comment by ssuperczynski** [comment]
Could you show `System` configuration from index.html. In my case this is correct one:

```js
    <script>
        System.config({
            map: {
                'ng2-easy-table': 'node_modules/ng2-easy-table/dist'
            },
            packages: {
                dist: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'ng2-easy-table': {
                    format: 'register',
                    defaultExtension: 'js'
                }
            }
        });
        System.import('dist/app/app.component')
                .then(null, console.error.bind(console));
    </script>
```

**Comment by ssuperczynski** [comment]
Hi @robertellis100, does it work now? Today I am upgrading library to angular-rc1, so couple of files will change

**Comment by ssuperczynski** [comment]
Closed, as new release include angular2-rc1 instead of beta17
