### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by nitinkumarmishra** [ssuperczynski/ng2-easy-table#29]
not able to install ng2-easy-table by running command `npm install ng2-easy-table`. here is the error
`> ng2-easy-table@0.1.15 postinstall /Users/nitin/Sites/projects/ani-theme-angular2-bootstrap4/node_modules/ng2-easy-table
> concurrently "typings install" "npm run tsc"

sh: concurrently: command not found
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ng2-easy-table" "--save"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ng2-easy-table@0.1.15 postinstall: `concurrently "typings install" "npm run tsc" `
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ng2-easy-table@0.1.15 postinstall script 'concurrently "typings install" "npm run tsc" '.
npm ERR! This is most likely a problem with the ng2-easy-table package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "typings install" "npm run tsc"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-easy-table
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ng2-easy-table
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nitin/Sites/projects/ani-theme-angular2-bootstrap4/npm-debug.log`

**Comment by aosmialowski** [comment]
You may need to install [https://www.npmjs.com/package/concurrently](concurrently) library from npm globally.

@ssuperczynski I was able to reproduce the issue. The `concurrently` library was not installed with other `devDependencies`.

**Comment by ssuperczynski** [comment]
Version 0.1.16 is available
