### ISSUE TITLE
Migrate project to Angular 4 and angular-cli

### ISSUE THREAD

**Issue by ssuperczynski** [ssuperczynski/ng2-easy-table#42]
Resurrection. It's time! #43

**Comment by yasirunilan** [comment]
This requires changing the dependencies to angular 4 right?

**Comment by ssuperczynski** [comment]
I almost finished it https://github.com/ssuperczynski/ng2-easy-table/pull/43

**Comment by ssuperczynski** [comment]
Project has been migrated, and is available under https://www.npmjs.com/package/ngx-easy-table
